site:
  title: Couchbase Documentation Style Guide
  url: https://labs.couchbase.com/style-guide-site
content:
  sources:
  - url: .
    branches: HEAD
    start_path: styleguidepages
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable 
    snapshot: true
